services:
  postgres:
    image: postgres:16-alpine
    container_name: schoolaris-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: schoolaris
      POSTGRES_PASSWORD: schoolaris123
      POSTGRES_DB: schoolaris
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
