services:
  postgres:
    image: postgres:16-alpine
    container_name: kursus-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kursus
      POSTGRES_PASSWORD: kursus123
      POSTGRES_DB: kursus
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
